#let terms = (
  (slug: "term-definition", title: [Definition], body: [A reusable tool contract containing a validated name, an input codec, and either an output codec or content-only output.]),
  (slug: "term-bound-tool", title: [Bound tool], body: [A definition joined to an application handler before heterogeneous registration erases the handler's native types.]),
  (slug: "term-server", title: [Server description], body: [An immutable catalog of bound tools, resources, prompts, completion, identity, and tool access policy.]),
  (slug: "term-exchange", title: [Exchange], body: [One inbound frame's response destination and the lifecycle of output to that destination.]),
  (slug: "term-invocation", title: [Invocation], body: [One admitted unit of application handler work, identified independently of its client's wire request id.]),
  (slug: "term-request-id", title: [Request id], body: [The client-selected string or integer echoed inside a JSON-RPC response. It is neither execution identity nor authenticated authority.]),
  (slug: "term-reducer", title: [Reducer], body: [A pure transition over one connection's protocol state that returns effects for an authoritative interpreter.]),
  (slug: "term-runtime", title: [Runtime], body: [The actor owning one reducer history and supervising the invocation processes that interpret its effects.]),
  (slug: "term-endpoint", title: [Endpoint], body: [The HTTP owner of the current server description, admitted request slots, active streams, and an optional listener.]),
  (slug: "term-grant", title: [Grant], body: [An admitted principal, exact protected resource, and actual attested scopes accepted by Relay's resource-server policy.]),
  (slug: "term-attestation", title: [Attestation], body: [A configured verifier's assertion about a token's principal, audiences, and scopes. Construction is not proof of cryptographic verification.]),
  (slug: "term-protection", title: [Protection], body: [The configured resource and endpoint scopes against which an attestation is admitted, together with authorization-server metadata.]),
  (slug: "term-context", title: [Application context], body: [The caller-owned native value supplied to listing policy and handler invocation for one request.]),
  (slug: "term-correlation", title: [Correlation], body: [A Sinal value joining observations across a request and its downstream work. A carried value is untrusted telemetry rather than identity.]),
  (slug: "term-idempotency-key", title: [Idempotency key], body: [An optional client assertion that repeated requests refer to one logical operation. The application determines identity using the authenticated principal and key.]),
  (slug: "term-evidence", title: [Submission evidence], body: [The client's knowledge that a request was NotSent, MaybeSent, or completed its protocol exchange. It does not establish the application's effect outcome.]),
  (slug: "term-continuation", title: [Continuation], body: [The originating client, operation, arguments, signed request state, and required responses retained for a subsequent tool input round.]),
  (slug: "term-subscription", title: [Subscription], body: [One owned listen request with an acknowledged notification filter and a cancellable stream lifetime.]),
  (slug: "term-cursor", title: [Cursor], body: [An opaque server-authenticated reference to a position in one listing family. Catalog and authorization-view binding remain required refinements.]),
  (slug: "term-tombstone", title: [Tombstone], body: [A retained terminal identity suppressing late or repeated work during a bounded retention interval.]),
  (slug: "term-cancellation-grace", title: [Cancellation grace], body: [The interval after a handler receives cancellation and before Relay kills a handler that has not returned.]),
  (slug: "term-protocol-schema", title: [Protocol schema], body: [The frozen revision's authority for JSON-RPC envelopes, method parameters, declarations, and result fields.]),
  (slug: "term-input-contract", title: [Input contract], body: [A Blueprint contract loaded from a tool's application input schema for local argument validation. Admission to Blueprint's finite profile is separate from MCP protocol validity.]),
)
